### ISSUE TITLE
查询时报错

### ISSUE THREAD

**Issue by EsuRt** [gitsang/goldendict-llm#1]
修改了config.yaml，查询时报错，具体信息如下：
`查询错误：程序返回，退出代码为 2. panic: adapter OpenRouter not found goroutine 1 [running]: main.run() D:/Application/GoldenDict/plugins/goldendict-llm/main.go:134 +0xaee main.init.0.func1(0xc0000fc700?, {0xc000181380?, 0x4?, 0xa59486?}) D:/Application/GoldenDict/plugins/goldendict-llm/main.go:61 +0x65 github.com/spf13/cobra.(*Command).execute(0xe84720, {0xc000092110, 0x3, 0x3}) D:/Users/yl2356/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1019 +0xa7b github.com/spf13/cobra.(*Command).ExecuteC(0xe84720) D:/Users/yl2356/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148 +0x40c github.com/spf13/cobra.(*Command).Execute(...) D:/Users/yl2356/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1071 main.main() D:/Application/GoldenDict/plugins/goldendict-llm/main.go:200 +0x1a`

**Comment by gitsang** [comment]
你可以贴上你的配置文件吗（注意隐藏 Token）？我猜测你选择了 OpenRouter 作为 Adapter，但并没有在 Adapters 中定义 OpenRouter。

**Comment by EsuRt** [comment]
发现把OpenRouter改成openai就可以了，原来是这样的：
```
adapter: OpenRouter

adapters:
  openai:
    url: "https://openrouter.ai/api/v1/chat/completions"
    token: "xxxxxxxxx"
    model: "deepseek/deepseek-chat"
```
